import { FolderTheme, FolderType, IconPack } from '../models';

/**
 * Defines folder icons
 */
export const folderIcons: FolderTheme[] = [
  getFolderThemeWithIcons('specific'),
  getFolderThemeWithIcons('colorful'),
  {
    name: 'classic',
    defaultIcon: { name: 'folder' },
    rootFolder: { name: 'folder-root' },
  },
  { name: 'none', defaultIcon: { name: '' } },
];

function getFolderThemeWithIcons(type: FolderType): FolderTheme {
  let prefix = `${type}-folder`;

  if (type === 'specific') {
    prefix = 'folder';
  }

  return {
    name: type,
    defaultIcon: { name: 'folder' },
    rootFolder: { name: 'folder-root' },
    icons: [
      {
        name: `${prefix}-robot`,
        folderNames: ['bot', 'robot', '.bot', '.robot', '_bot', '_robot'],
      },
      {
        name: `${prefix}-src`,
        folderNames: ['src', 'srcs', 'source', 'sources', 'code'],
      },
      {
        name: `${prefix}-dist`,
        folderNames: ['dist', 'out', 'build', 'release', 'bin'],
      },
      {
        name: `${prefix}-css`,
        folderNames: ['css', 'stylesheet', 'stylesheets', 'style', 'styles'],
      },
      {
        name: `${prefix}-sass`,
        folderNames: ['sass', '_sass', 'scss', '_scss'],
      },
      { name: `${prefix}-television`, folderNames: ['tv', 'television'] },
      { name: `${prefix}-desktop`, folderNames: ['desktop'] },
      { name: `${prefix}-console`, folderNames: ['console'] },
      {
        name: `${prefix}-images`,
        folderNames: [
          '_images',
          '_image',
          '_imgs',
          '_img',
          'images',
          'image',
          'imgs',
          'img',
          'icons',
          'icon',
          'icos',
          'ico',
          'figures',
          'figure',
          'figs',
          'fig',
          'screenshot',
          'screenshots',
          'screengrab',
          'screengrabs',
          'pic',
          'pics',
          'picture',
          'pictures',
          'photo',
          'photos',
          'photograph',
          'photographs',
        ],
      },
      {
        name: `${prefix}-scripts`,
        folderNames: ['script', 'scripts', 'scripting'],
      },
      { name: `${prefix}-node`, folderNames: ['node_modules'] },
      {
        name: `${prefix}-javascript`,
        folderNames: ['js', 'javascript', 'javascripts'],
      },
      { name: `${prefix}-json`, folderNames: ['json', 'jsons'] },
      { name: `${prefix}-font`, folderNames: ['font', 'fonts'] },
      { name: `${prefix}-bower`, folderNames: ['bower_components'] },
      {
        name: `${prefix}-test`,
        folderNames: [
          'test',
          'tests',
          'testing',
          '__tests__',
          '__snapshots__',
          '__mocks__',
          '__fixtures__',
          '__test__',
          'spec',
          'specs',
        ],
      },
      {
        name: `${prefix}-jinja`,
        folderNames: ['jinja', 'jinja2', 'j2'],
        light: true,
      },
      { name: `${prefix}-markdown`, folderNames: [`markdown`, `md`] },
      { name: `${prefix}-pdm`, folderNames: ['.pdm-plugins', '.pdm-build'] },
      { name: `${prefix}-php`, folderNames: [`php`] },
      { name: `${prefix}-phpmailer`, folderNames: [`phpmailer`] },
      { name: `${prefix}-sublime`, folderNames: [`sublime`] },
      {
        name: `${prefix}-docs`,
        folderNames: [
          '_post',
          '_posts',
          'doc',
          'docs',
          'document',
          'documents',
          'documentation',
          'post',
          'posts',
          'article',
          'articles',
        ],
      },
      {
        name: `${prefix}-git`,
        folderNames: [
          '.git',
          'patches',
          'githooks',
          '.githooks',
          'submodules',
          '.submodules',
        ],
      },
      { name: `${prefix}-github`, folderNames: ['.github', 'github'] },
      { name: `${prefix}-gitlab`, folderNames: ['.gitlab'] },
      { name: `${prefix}-vscode`, folderNames: ['.vscode', '.vscode-test'] },
      {
        name: `${prefix}-views`,
        folderNames: [
          'view',
          'views',
          'screen',
          'screens',
          'page',
          'pages',
          'public_html',
          'html',
        ],
      },
      { name: `${prefix}-vue`, folderNames: ['vue'] },
      { name: `${prefix}-vuepress`, folderNames: ['.vuepress'] },
      { name: `${prefix}-expo`, folderNames: ['.expo', '.expo-shared'] },
      {
        name: `${prefix}-config`,
        folderNames: [
          'cfg',
          'cfgs',
          'conf',
          'confs',
          '.config',
          'config',
          'configs',
          'configuration',
          'configurations',
          'setting',
          '.setting',
          'settings',
          '.settings',
          'META-INF',
          'option',
          'options',
        ],
      },
      {
        name: `${prefix}-i18n`,
        folderNames: [
          'i18n',
          'internationalization',
          'lang',
          'langs',
          'language',
          'languages',
          'locale',
          'locales',
          'l10n',
          'localization',
          'translation',
          'translate',
          'translations',
          '.tx',
        ],
      },
      {
        name: `${prefix}-components`,
        folderNames: ['components', 'widget', 'widgets', 'fragments'],
      },
      {
        name: `${prefix}-verdaccio`,
        folderNames: ['.verdaccio', 'verdaccio'],
      },
      { name: `${prefix}-aurelia`, folderNames: ['aurelia_project'] },
      {
        name: `${prefix}-resource`,
        folderNames: [
          'resource',
          'resources',
          'res',
          'asset',
          'assets',
          'static',
          'report',
          'reports',
        ],
      },
      {
        name: `${prefix}-lib`,
        folderNames: [
          'lib',
          'libs',
          'library',
          'libraries',
          'vendor',
          'vendors',
          'third-party',
        ],
      },
      {
        name: `${prefix}-theme`,
        folderNames: [
          'themes',
          'theme',
          'color',
          'colors',
          'design',
          'designs',
        ],
      },
      { name: `${prefix}-webpack`, folderNames: ['webpack', '.webpack'] },
      { name: `${prefix}-global`, folderNames: ['global'] },
      {
        name: `${prefix}-public`,
        folderNames: [
          '_site',
          'public',
          'www',
          'wwwroot',
          'web',
          'website',
          'site',
          'browser',
          'browsers',
        ],
      },
      {
        name: `${prefix}-include`,
        folderNames: [
          'include',
          'includes',
          '_includes',
          'inc',
          'partials',
          '_partials',
        ],
      },
      {
        name: `${prefix}-docker`,
        folderNames: ['docker', 'dockerfiles', '.docker'],
      },
      {
        name: `${prefix}-ngrx-effects`,
        folderNames: ['effects'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-ngrx-store`,
        folderNames: ['store'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-ngrx-state`,
        folderNames: ['states', 'state'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-ngrx-reducer`,
        folderNames: ['reducers', 'reducer'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-ngrx-actions`,
        folderNames: ['actions'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-ngrx-entities`,
        folderNames: ['entities'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-ngrx-selectors`,
        folderNames: ['selectors'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: `${prefix}-redux-reducer`,
        folderNames: ['reducers', 'reducer'],
        enabledFor: [IconPack.Redux],
      },
      {
        name: `${prefix}-redux-actions`,
        folderNames: ['actions'],
        enabledFor: [IconPack.Redux],
      },
      {
        name: `${prefix}-redux-selector`,
        folderNames: ['selectors', 'selector'],
        enabledFor: [IconPack.Redux],
      },
      {
        name: `${prefix}-redux-store`,
        folderNames: ['store', 'stores'],
        enabledFor: [IconPack.Redux],
      },
      {
        name: `${prefix}-react-components`,
        folderNames: ['components', 'react', 'jsx', 'reactjs'],
        enabledFor: [IconPack.React, IconPack.Redux],
      },
      {
        name: `${prefix}-database`,
        folderNames: ['db', 'database', 'databases', 'sql', 'data', '_data'],
      },
      { name: `${prefix}-log`, folderNames: ['log', 'logs', 'logging'] },
      { name: `${prefix}-target`, folderNames: ['target'] },
      {
        name: `${prefix}-temp`,
        folderNames: [
          'temp',
          '.temp',
          'tmp',
          '.tmp',
          'cached',
          'cache',
          '.cache',
        ],
      },
      { name: `${prefix}-aws`, folderNames: ['aws', '.aws'] },
      {
        name: `${prefix}-audio`,
        folderNames: [
          'aud',
          'auds',
          'audio',
          'audios',
          'music',
          'sound',
          'sounds',
        ],
      },
      {
        name: `${prefix}-video`,
        folderNames: ['vid', 'vids', 'video', 'videos', 'movie', 'movies'],
      },
      {
        name: `${prefix}-kubernetes`,
        folderNames: ['kubernetes', '.kubernetes', 'k8s', '.k8s'],
      },
      {
        name: `${prefix}-import`,
        folderNames: ['import', 'imports', 'imported'],
      },
      {
        name: `${prefix}-export`,
        folderNames: ['export', 'exports', 'exported'],
      },
      { name: `${prefix}-wakatime`, folderNames: ['wakatime'] },
      { name: `${prefix}-circleci`, folderNames: ['.circleci'] },
      {
        name: `${prefix}-wordpress`,
        folderNames: ['.wordpress-org', 'wp-content'],
      },
      { name: `${prefix}-gradle`, folderNames: ['gradle', '.gradle'] },
      {
        name: `${prefix}-coverage`,
        folderNames: [
          'coverage',
          '.nyc-output',
          '.nyc_output',
          'e2e',
          'it',
          'integration-test',
          'integration-tests',
          '__integration-test__',
          '__integration-tests__',
        ],
      },
      {
        name: `${prefix}-class`,
        folderNames: [
          'class',
          'classes',
          'model',
          'models',
          'schemas',
          'schema',
        ],
      },
      {
        name: `${prefix}-other`,
        folderNames: [
          'other',
          'others',
          'misc',
          'miscellaneous',
          'extra',
          'extras',
          'etc',
        ],
      },
      { name: `${prefix}-lua`, folderNames: ['lua'] },
      {
        name: `${prefix}-typescript`,
        folderNames: ['typescript', 'ts', 'typings', '@types', 'types'],
      },
      { name: `${prefix}-graphql`, folderNames: ['graphql', 'gql'] },
      {
        name: `${prefix}-routes`,
        folderNames: ['routes', 'router', 'routers'],
      },
      { name: `${prefix}-ci`, folderNames: ['.ci', 'ci'] },
      {
        name: `${prefix}-benchmark`,
        folderNames: [
          'benchmark',
          'benchmarks',
          'performance',
          'measure',
          'measures',
          'measurement',
        ],
      },
      {
        name: `${prefix}-messages`,
        folderNames: [
          'messages',
          'messaging',
          'forum',
          'chat',
          'chats',
          'conversation',
          'conversations',
        ],
      },
      { name: `${prefix}-less`, folderNames: ['less'] },
      {
        name: `${prefix}-gulp`,
        folderNames: [
          'gulp',
          'gulp-tasks',
          'gulpfile.js',
          'gulpfile.mjs',
          'gulpfile.ts',
          'gulpfile.babel.js',
        ],
      },
      {
        name: `${prefix}-python`,
        folderNames: ['python', '__pycache__', '.pytest_cache'],
      },
      {
        name: `${prefix}-mojo`,
        folderNames: ['mojo'],
      },
      { name: `${prefix}-moon`, folderNames: ['.moon'] },
      { name: `${prefix}-debug`, folderNames: ['debug', 'debugging'] },
      { name: `${prefix}-fastlane`, folderNames: ['fastlane'] },
      {
        name: `${prefix}-plugin`,
        folderNames: [
          'plugin',
          'plugins',
          '_plugins',
          'mod',
          'mods',
          'modding',
          'extension',
          'extensions',
          'addon',
          'addons',
          'module',
          'modules',
        ],
      },
      {
        name: `${prefix}-middleware`,
        folderNames: ['middleware', 'middlewares'],
      },
      {
        name: `${prefix}-controller`,
        folderNames: [
          'controller',
          'controllers',
          'service',
          'services',
          'provider',
          'providers',
          'handler',
          'handlers',
        ],
      },
      { name: `${prefix}-ansible`, folderNames: ['ansible'] },
      {
        name: `${prefix}-server`,
        folderNames: ['server', 'servers', 'backend'],
      },
      {
        name: `${prefix}-client`,
        folderNames: ['client', 'clients', 'frontend', 'frontends', 'pwa'],
      },
      { name: `${prefix}-tasks`, folderNames: ['tasks', 'tickets'] },
      { name: `${prefix}-android`, folderNames: ['android'] },
      { name: `${prefix}-ios`, folderNames: ['ios'] },
      { name: `${prefix}-upload`, folderNames: ['uploads', 'upload'] },
      { name: `${prefix}-download`, folderNames: ['downloads', 'download'] },
      {
        name: `${prefix}-tools`,
        folderNames: [
          'tools',
          'toolkit',
          'toolkits',
          'toolbox',
          'toolboxes',
          'tooling',
        ],
      },
      { name: `${prefix}-helper`, folderNames: ['helpers', 'helper'] },
      {
        name: `${prefix}-serverless`,
        folderNames: ['.serverless', 'serverless'],
      },
      { name: `${prefix}-api`, folderNames: ['api', 'apis', 'restapi'] },
      { name: `${prefix}-app`, folderNames: ['app', 'apps'] },
      {
        name: `${prefix}-apollo`,
        folderNames: [
          'apollo',
          'apollo-client',
          'apollo-cache',
          'apollo-config',
        ],
      },
      {
        name: `${prefix}-archive`,
        folderNames: [
          'arc',
          'arcs',
          'archive',
          'archives',
          'archival',
          'bkp',
          'bkps',
          'bak',
          'baks',
          'backup',
          'backups',
          'back-up',
          'back-ups',
          'history',
          'histories',
        ],
      },
      { name: `${prefix}-batch`, folderNames: ['batch', 'batchs', 'batches'] },
      { name: `${prefix}-buildkite`, folderNames: ['buildkite', '.buildkite'] },
      { name: `${prefix}-cluster`, folderNames: ['cluster', 'clusters'] },
      {
        name: `${prefix}-command`,
        folderNames: ['command', 'commands', 'cmd', 'cli', 'clis'],
      },
      { name: `${prefix}-constant`, folderNames: ['constant', 'constants'] },
      {
        name: `${prefix}-container`,
        folderNames: ['container', 'containers', '.devcontainer'],
      },
      { name: `${prefix}-content`, folderNames: ['content', 'contents'] },
      { name: `${prefix}-context`, folderNames: ['context', 'contexts'] },
      { name: `${prefix}-core`, folderNames: ['core'] },
      { name: `${prefix}-delta`, folderNames: ['delta', 'deltas', 'changes'] },
      { name: `${prefix}-dump`, folderNames: ['dump', 'dumps'] },
      {
        name: `${prefix}-examples`,
        folderNames: [
          'demo',
          'demos',
          'example',
          'examples',
          'sample',
          'samples',
          'sample-data',
        ],
      },
      {
        name: `${prefix}-environment`,
        folderNames: [
          '.env',
          '.environment',
          'env',
          'envs',
          'environment',
          'environments',
          '.venv',
        ],
      },
      {
        name: `${prefix}-functions`,
        folderNames: [
          'func',
          'funcs',
          'function',
          'functions',
          'lambda',
          'lambdas',
          'logic',
          'math',
          'maths',
          'calc',
          'calcs',
          'calculation',
          'calculations',
        ],
      },
      {
        name: `${prefix}-generator`,
        folderNames: [
          'generator',
          'generators',
          'generated',
          'cfn-gen',
          'gen',
          'gens',
          'auto',
        ],
      },
      {
        name: `${prefix}-hook`,
        folderNames: ['hook', 'hooks', 'trigger', 'triggers'],
      },
      { name: `${prefix}-job`, folderNames: ['job', 'jobs'] },
      {
        name: `${prefix}-keys`,
        folderNames: [
          'key',
          'keys',
          'token',
          'tokens',
          'jwt',
          'secret',
          'secrets',
        ],
      },
      {
        name: `${prefix}-layout`,
        folderNames: ['layout', 'layouts', '_layouts'],
      },
      {
        name: `${prefix}-mail`,
        folderNames: ['mail', 'mails', 'email', 'emails', 'smtp', 'mailers'],
      },
      { name: `${prefix}-mappings`, folderNames: ['mappings', 'mapping'] },
      { name: `${prefix}-meta`, folderNames: ['meta'] },
      {
        name: `${prefix}-changesets`,
        folderNames: ['.changesets', '.changeset'],
      },
      {
        name: `${prefix}-packages`,
        folderNames: ['package', 'packages', 'pkg', 'pkgs'],
      },
      { name: `${prefix}-shared`, folderNames: ['shared', 'common'] },
      {
        name: `${prefix}-shader`,
        folderNames: ['glsl', 'hlsl', 'shader', 'shaders'],
      },
      { name: `${prefix}-stack`, folderNames: ['stack', 'stacks'] },
      { name: `${prefix}-template`, folderNames: ['template', 'templates'] },
      {
        name: `${prefix}-utils`,
        folderNames: ['util', 'utils', 'utility', 'utilities'],
      },
      { name: `${prefix}-supabase`, folderNames: ['supabase', '.supabase'] },
      { name: `${prefix}-private`, folderNames: ['private', '.private'] },
      { name: `${prefix}-linux`, folderNames: ['linux'] },
      { name: `${prefix}-windows`, folderNames: ['windows'] },
      { name: `${prefix}-macos`, folderNames: ['macos', '.DS_Store'] },
      {
        name: `${prefix}-error`,
        folderNames: ['error', 'errors', 'err', 'errs', 'crash', 'crashes'],
      },
      { name: `${prefix}-event`, folderNames: ['event', 'events'] },
      {
        name: `${prefix}-secure`,
        folderNames: [
          'auth',
          'authentication',
          'secure',
          'security',
          'cert',
          'certs',
          'certificate',
          'certificates',
          'ssl',
        ],
      },
      { name: `${prefix}-custom`, folderNames: ['custom', 'customs'] },
      {
        name: `${prefix}-mock`,
        folderNames: [
          '_draft',
          '_drafts',
          'mock',
          'mocks',
          'fixture',
          'fixtures',
          'draft',
          'drafts',
          'concept',
          'concepts',
          'sketch',
          'sketches',
        ],
      },
      {
        name: `${prefix}-syntax`,
        folderNames: ['syntax', 'syntaxes', 'spellcheck'],
      },
      { name: `${prefix}-vm`, folderNames: ['vm', 'vms'] },
      { name: `${prefix}-stylus`, folderNames: ['stylus'] },
      { name: `${prefix}-flow`, folderNames: ['flow-typed'] },
      {
        name: `${prefix}-rules`,
        folderNames: [
          'rule',
          'rules',
          'validation',
          'validations',
          'validator',
          'validators',
        ],
      },
      {
        name: `${prefix}-review`,
        folderNames: ['review', 'reviews', 'revisal', 'revisals', 'reviewed'],
      },
      {
        name: `${prefix}-animation`,
        folderNames: ['anim', 'anims', 'animation', 'animations', 'animated'],
      },
      { name: `${prefix}-guard`, folderNames: ['guard', 'guards'] },
      { name: `${prefix}-prisma`, folderNames: ['prisma'] },
      { name: `${prefix}-pipe`, folderNames: ['pipe', 'pipes'] },
      { name: `${prefix}-svg`, folderNames: ['svg', 'svgs'] },
      {
        name: `${prefix}-vuex-store`,
        folderNames: ['store', 'stores'],
        enabledFor: [IconPack.Vuex],
      },
      {
        name: `${prefix}-nuxt`,
        folderNames: ['nuxt', '.nuxt'],
        enabledFor: [IconPack.Vuex, IconPack.Vue],
      },
      {
        name: `${prefix}-vue-directives`,
        folderNames: ['directives'],
        enabledFor: [IconPack.Vuex, IconPack.Vue],
      },
      {
        name: `${prefix}-vue`,
        folderNames: ['components'],
        enabledFor: [IconPack.Vuex, IconPack.Vue],
      },
      { name: `${prefix}-terraform`, folderNames: ['terraform', '.terraform'] },
      {
        name: `${prefix}-mobile`,
        folderNames: ['mobile', 'mobiles', 'portable', 'portability'],
      },
      { name: `${prefix}-stencil`, folderNames: ['.stencil'] },
      { name: `${prefix}-firebase`, folderNames: ['firebase', '.firebase'] },
      { name: `${prefix}-svelte`, folderNames: ['svelte', '.svelte-kit'] },
      {
        name: `${prefix}-update`,
        folderNames: ['update', 'updates', 'upgrade', 'upgrades'],
      },
      { name: `${prefix}-intellij`, folderNames: ['.idea'], light: true },
      {
        name: `${prefix}-azure-pipelines`,
        folderNames: ['.azure-pipelines', '.azure-pipelines-ci'],
      },
      { name: `${prefix}-mjml`, folderNames: ['mjml'] },
      {
        name: `${prefix}-admin`,
        folderNames: [
          'admin',
          'admins',
          'manager',
          'managers',
          'moderator',
          'moderators',
        ],
      },
      { name: `${prefix}-scala`, folderNames: ['scala'] },
      {
        name: `${prefix}-connection`,
        folderNames: [
          'connection',
          'connections',
          'integration',
          'integrations',
        ],
      },
      { name: `${prefix}-quasar`, folderNames: ['.quasar'] },
      { name: `${prefix}-next`, folderNames: ['.next'] },
      { name: `${prefix}-cobol`, folderNames: ['cobol'] },
      { name: `${prefix}-yarn`, folderNames: ['yarn', '.yarn'] },
      { name: `${prefix}-husky`, folderNames: ['husky', '.husky'] },
      {
        name: `${prefix}-storybook`,
        folderNames: ['.storybook', 'storybook', 'stories', '__stories__'],
      },
      { name: `${prefix}-base`, folderNames: ['base', '.base', 'bases'] },
      {
        name: `${prefix}-cart`,
        folderNames: ['cart', 'shopping-cart', 'shopping', 'shop'],
      },
      {
        name: `${prefix}-home`,
        folderNames: ['home', '.home', 'start', '.start'],
      },
      {
        name: `${prefix}-project`,
        folderNames: ['project', 'projects', '.project', '.projects'],
      },
      {
        name: `${prefix}-interface`,
        folderNames: ['interface', 'interfaces'],
      },
      { name: `${prefix}-netlify`, folderNames: ['.netlify'] },
      {
        name: `${prefix}-enum`,
        folderNames: ['enum', 'enums'],
      },
      {
        name: `${prefix}-contract`,
        folderNames: [
          'pact',
          'pacts',
          'contract',
          '.contract',
          'contracts',
          'contract-testing',
          'contract-test',
          'contract-tests',
        ],
      },
      {
        name: `${prefix}-queue`,
        folderNames: ['queue', 'queues', 'bull', 'mq'],
      },
      {
        name: `${prefix}-vercel`,
        folderNames: ['vercel', '.vercel', 'now', '.now'],
      },
      {
        name: `${prefix}-cypress`,
        folderNames: ['cypress', '.cypress'],
      },
      {
        name: `${prefix}-decorators`,
        folderNames: ['decorator', 'decorators'],
      },
      {
        name: `${prefix}-java`,
        folderNames: ['java'],
      },
      {
        name: `${prefix}-resolver`,
        folderNames: ['resolver', 'resolvers'],
      },
      {
        name: `${prefix}-angular`,
        folderNames: ['angular', '.angular'],
      },
      {
        name: `${prefix}-unity`,
        folderNames: ['unity'],
      },
      {
        name: `${prefix}-pdf`,
        folderNames: ['pdf', 'pdfs'],
      },
      {
        name: `${prefix}-proto`,
        folderNames: ['protobuf', 'protobufs', 'proto', 'protos'],
      },
      {
        name: `${prefix}-plastic`,
        folderNames: ['plastic', '.plastic'],
      },
      {
        name: `${prefix}-gamemaker`,
        folderNames: ['gamemaker', 'gamemaker2'],
      },
      {
        name: `${prefix}-mercurial`,
        folderNames: ['.hg', 'hghooks', '.hghooks', '.hgext'],
      },
      {
        name: `${prefix}-godot`,
        folderNames: ['godot', '.godot', 'godot-cpp', '.godot-cpp'],
      },
      {
        name: `${prefix}-lottie`,
        folderNames: ['lottie', 'lotties', 'lottiefiles'],
      },
      {
        name: `${prefix}-taskfile`,
        folderNames: ['taskfile', 'taskfiles', '.taskfile', '.taskfiles'],
      },
      {
        name: `${prefix}-cloudflare`,
        folderNames: ['cloudflare', '.cloudflare'],
      },
    ],
  };
}
