import type { FolderTheme } from '../models/icons/folders/folderTheme';
import type { FolderType } from '../models/icons/folders/folderType';
import { IconPack } from '../models/icons/iconPack';

/**
 * Defines folder icons
 */
export const folderIcons: FolderTheme[] = [
  getFolderIcons('specific'),
  getFolderIcons('colorful'),
  {
    name: 'classic',
    defaultIcon: { name: 'folder' },
    rootFolder: { name: 'folder-root' },
  },
  { name: 'none', defaultIcon: { name: '' } },
];

function getFolderIcons(type: FolderType): FolderTheme {
  let prefix = `${type}-folder`;

  if (type === 'specific') {
    prefix = 'folder';
  }

  function createBase(name: string) {
    return `${prefix}-${name}`;
  }

  function createCloneColor(color: string) {
    let base = '';
    if (type === 'specific') base = `${color}Base`;
    if (type === 'colorful') base = `${color}Dim`;
    return base;
  }

  return {
    name: type,
    defaultIcon: { name: 'folder' },
    rootFolder: { name: 'folder-root' },
    icons: [
      { name: createBase('rust'), folderNames: ['rust'] },
      {
        name: createBase('robot'),
        folderNames: ['bot', 'bots', 'robot', 'robots', 'agent', 'agents'],
      },
      {
        name: createBase('src'),
        folderNames: ['src', 'srcs', 'source', 'sources', 'code'],
      },
      {
        name: createBase('dist'),
        folderNames: [
          'dist',
          'out',
          'output',
          'outputs',
          'build',
          'builds',
          'release',
          'bin',
          'distribution',
          'built',
          'compiled',
        ],
      },
      {
        name: createBase('css'),
        folderNames: ['css', 'stylesheet', 'stylesheets', 'style', 'styles'],
      },
      { name: createBase('sass'), folderNames: ['sass', 'scss'] },
      { name: createBase('television'), folderNames: ['tv', 'television'] },
      { name: createBase('desktop'), folderNames: ['desktop', 'display'] },
      {
        name: createBase('console'),
        folderNames: [
          'console',
          'xbox',
          'ps4',
          'ps5',
          'switch',
          'game',
          'games',
        ],
      },
      {
        name: createBase('images'),
        folderNames: [
          'images',
          'image',
          'imgs',
          'img',
          'icons',
          'icon',
          'icos',
          'ico',
          'figures',
          'figure',
          'figs',
          'fig',
          'screenshot',
          'screenshots',
          'screengrab',
          'screengrabs',
          'pic',
          'pics',
          'picture',
          'pictures',
          'photo',
          'photos',
          'photograph',
          'photographs',
          'texture',
          'textures',
        ],
      },
      {
        name: createBase('scripts'),
        folderNames: ['script', 'scripts', 'scripting'],
      },
      {
        name: createBase('node'),
        folderNames: ['node', 'nodejs', 'node_modules'],
      },
      {
        name: createBase('javascript'),
        folderNames: ['js', 'javascript', 'javascripts', 'cjs', 'mjs'],
      },
      {
        name: createBase('json'),
        folderNames: ['json', 'jsons', 'jsonc', 'jsonl'],
      },
      {
        name: createBase('font'),
        folderNames: ['font', 'fonts', 'typeface', 'typefaces'],
      },
      { name: createBase('bower'), folderNames: ['bower_components'] },
      {
        name: createBase('test'),
        folderNames: [
          'test',
          'tests',
          'testing',
          'snapshots',
          'spec',
          'specs',
          'testfiles',
        ],
      },
      {
        name: createBase('directive'),
        folderNames: ['directive', 'directives'],
      },
      {
        name: createBase('jinja'),
        folderNames: ['jinja', 'jinja2', 'j2'],
        light: true,
      },
      { name: createBase('markdown'), folderNames: ['markdown', 'md'] },
      { name: createBase('pdm'), folderNames: ['pdm-plugins', 'pdm-build'] },
      { name: createBase('php'), folderNames: ['php'] },
      { name: createBase('phpmailer'), folderNames: ['phpmailer'] },
      { name: createBase('sublime'), folderNames: ['sublime'] },
      {
        name: createBase('docs'),
        folderNames: [
          'doc',
          'docs',
          'document',
          'documents',
          'documentation',
          'post',
          'posts',
          'article',
          'articles',
          'wiki',
          'news',
          'blog',
          'knowledge',
          'diary',
          'note',
          'notes',
        ],
      },
      { name: createBase('gh-workflows'), folderNames: ['github/workflows'] },
      {
        name: createBase('git'),
        folderNames: ['git', 'patches', 'githooks', 'submodules'],
      },
      { name: createBase('github'), folderNames: ['github'] },
      { name: createBase('gitea'), folderNames: ['gitea'] },
      { name: createBase('gitlab'), folderNames: ['gitlab'] },
      { name: createBase('forgejo'), folderNames: ['forgejo'] },
      { name: createBase('vscode'), folderNames: ['vscode', 'vscode-test'] },
      {
        name: createBase('views'),
        folderNames: [
          'view',
          'views',
          'screen',
          'screens',
          'page',
          'pages',
          'public_html',
          'html',
        ],
      },
      { name: createBase('vue'), folderNames: ['vue'] },
      { name: createBase('vuepress'), folderNames: ['vuepress'] },
      { name: createBase('expo'), folderNames: ['expo', 'expo-shared'] },
      {
        name: createBase('config'),
        folderNames: [
          'cfg',
          'cfgs',
          'conf',
          'confs',
          'config',
          'configs',
          'configuration',
          'configurations',
          'setting',
          'settings',
          'META-INF',
          'option',
          'options',
          'pref',
          'prefs',
          'preference',
          'preferences',
          'props',
          'properties',
        ],
      },
      {
        name: createBase('i18n'),
        folderNames: [
          'i18n',
          'internationalization',
          'lang',
          'langs',
          'language',
          'languages',
          'locale',
          'locales',
          'l10n',
          'localization',
          'translation',
          'translate',
          'translations',
          'tx',
        ],
      },
      {
        name: createBase('components'),
        folderNames: ['components', 'widget', 'widgets', 'fragments'],
      },
      {
        name: createBase('verdaccio'),
        folderNames: ['verdaccio'],
      },
      { name: createBase('aurelia'), folderNames: ['aurelia_project'] },
      {
        name: createBase('resource'),
        folderNames: [
          'resource',
          'resources',
          'res',
          'asset',
          'assets',
          'static',
          'report',
          'reports',
        ],
      },
      {
        name: createBase('lib'),
        folderNames: [
          'lib',
          'libs',
          'library',
          'libraries',
          'vendor',
          'vendors',
          'third-party',
          'lib64',
        ],
      },
      {
        name: createBase('theme'),
        folderNames: [
          'themes',
          'theme',
          'color',
          'colors',
          'colour',
          'colours',
          'design',
          'designs',
          'palette',
          'palettes',
        ],
      },
      { name: createBase('webpack'), folderNames: ['webpack'] },
      { name: createBase('global'), folderNames: ['global'] },
      {
        name: createBase('public'),
        folderNames: [
          'public',
          'www',
          'wwwroot',
          'web',
          'website',
          'websites',
          'site',
          'browser',
          'browsers',
        ],
      },
      {
        name: createBase('include'),
        folderNames: [
          'inc',
          'include',
          'includes',
          'partial',
          'partials',
          'inc64',
        ],
      },
      {
        name: createBase('docker'),
        folderNames: ['docker', 'dockerfiles', 'dockerhub'],
      },
      {
        name: createBase('ngrx-store'),
        folderNames: ['store'],
        enabledFor: [IconPack.Ngrx],
      },
      {
        name: createBase('ngrx-effects'),
        folderNames: ['effects'],
        enabledFor: [IconPack.Ngrx],
        clone: {
          base: 'folder-ngrx-store',
          color: createCloneColor('cyan'),
        },
      },
      {
        name: createBase('ngrx-state'),
        folderNames: ['states', 'state'],
        enabledFor: [IconPack.Ngrx],
        clone: {
          base: 'folder-ngrx-store',
          color: createCloneColor('green'),
        },
      },
      {
        name: createBase('ngrx-reducer'),
        folderNames: ['reducers', 'reducer'],
        enabledFor: [IconPack.Ngrx],
        clone: {
          base: 'folder-ngrx-store',
          color: createCloneColor('red'),
        },
      },
      {
        name: createBase('ngrx-actions'),
        folderNames: ['actions'],
        enabledFor: [IconPack.Ngrx],
        clone: {
          base: 'folder-ngrx-store',
          color: createCloneColor('violet'),
        },
      },
      {
        name: createBase('ngrx-entities'),
        folderNames: ['entities'],
        enabledFor: [IconPack.Ngrx],
        clone: {
          base: 'folder-ngrx-store',
          color: createCloneColor('yellow'),
        },
      },
      {
        name: createBase('ngrx-selectors'),
        folderNames: ['selectors'],
        enabledFor: [IconPack.Ngrx],
        clone: {
          base: 'folder-ngrx-store',
          color: createCloneColor('orange'),
        },
      },
      {
        name: createBase('redux-reducer'),
        folderNames: ['reducers', 'reducer', 'redux-reducer', 'redux-reducers'],
        enabledFor: [IconPack.Redux],
      },
      {
        name: createBase('redux-actions'),
        folderNames: ['actions'],
        enabledFor: [IconPack.Redux],
        clone: {
          base: 'folder-redux-reducer',
          color: createCloneColor('violet'),
        },
      },
      {
        name: createBase('redux-toolkit'),
        folderNames: ['redux', 'redux-toolkit'],
        enabledFor: [IconPack.Redux],
        clone: {
          base: 'folder-redux-reducer',
          color: createCloneColor('violet'),
        },
      },
      {
        name: createBase('redux-selector'),
        folderNames: ['selectors', 'selector'],
        enabledFor: [IconPack.Redux],
        clone: {
          base: 'folder-redux-reducer',
          color: createCloneColor('orange'),
        },
      },
      {
        name: createBase('redux-store'),
        folderNames: ['store', 'stores'],
        enabledFor: [IconPack.Redux],
        clone: {
          base: 'folder-redux-reducer',
          color: createCloneColor('green'),
        },
      },
      {
        name: createBase('react-components'),
        folderNames: [
          'components',
          'react',
          'jsx',
          'reactjs',
          'react-components',
        ],
        enabledFor: [IconPack.React, IconPack.Redux],
      },
      {
        name: createBase('astro'),
        folderNames: ['astro'],
      },
      {
        name: createBase('database'),
        folderNames: ['db', 'data', 'database', 'databases', 'sql'],
      },
      {
        name: createBase('migrations'),
        folderNames: ['migrations', 'migration'],
      },
      { name: createBase('log'), folderNames: ['log', 'logs', 'logging'] },
      { name: createBase('target'), folderNames: ['target'] },
      {
        name: createBase('temp'),
        folderNames: ['temp', 'tmp', 'cached', 'cache'],
      },
      { name: createBase('aws'), folderNames: ['aws', 'azure', 'gcp'] },
      {
        name: createBase('audio'),
        folderNames: [
          'aud',
          'auds',
          'audio',
          'audios',
          'music',
          'song',
          'songs',
          'sound',
          'sounds',
          'voice',
          'voices',
          'recordings',
          'playlist',
          'playlists',
        ],
      },
      {
        name: createBase('video'),
        folderNames: [
          'vid',
          'vids',
          'video',
          'videos',
          'movie',
          'movies',
          'media',
        ],
      },
      {
        name: createBase('kubernetes'),
        folderNames: ['kubernetes', 'k8s'],
      },
      {
        name: createBase('import'),
        folderNames: ['import', 'imports', 'imported'],
      },
      {
        name: createBase('export'),
        folderNames: ['export', 'exports', 'exported'],
      },
      { name: createBase('wakatime'), folderNames: ['wakatime'] },
      { name: createBase('circleci'), folderNames: ['circleci'] },
      {
        name: createBase('wordpress'),
        folderNames: ['wordpress-org', 'wp-content'],
      },
      { name: createBase('gradle'), folderNames: ['gradle'] },
      {
        name: createBase('coverage'),
        folderNames: [
          'coverage',
          'nyc-output',
          'nyc_output',
          'e2e',
          'it',
          'integration-test',
          'integration-tests',
        ],
      },
      {
        name: createBase('class'),
        folderNames: [
          'class',
          'classes',
          'model',
          'models',
          'schemas',
          'schema',
        ],
      },
      {
        name: createBase('other'),
        folderNames: [
          'other',
          'others',
          'misc',
          'miscellaneous',
          'extra',
          'extras',
          'etc',
        ],
      },
      { name: createBase('lua'), folderNames: ['lua'] },
      { name: createBase('turborepo'), folderNames: ['turbo'] },
      {
        name: createBase('typescript'),
        folderNames: [
          'typescript',
          'ts',
          'typings',
          '@types',
          'types',
          'cts',
          'mts',
        ],
      },
      { name: createBase('graphql'), folderNames: ['graphql', 'gql'] },
      {
        name: createBase('routes'),
        folderNames: [
          'routes',
          'router',
          'routers',
          'navigation',
          'navigations',
          'routing',
        ],
      },
      { name: createBase('ci'), folderNames: ['ci'] },
      {
        name: createBase('eslint'),
        folderNames: [
          'eslint',
          'eslint-plugin',
          'eslint-plugins',
          'eslint-config',
          'eslint-configs',
        ],
      },
      {
        name: createBase('benchmark'),
        folderNames: [
          'benchmark',
          'benchmarks',
          'bench',
          'performance',
          'perf',
          'profiling',
          'measure',
          'measures',
          'measurement',
        ],
      },
      {
        name: createBase('messages'),
        folderNames: [
          'messages',
          'messaging',
          'forum',
          'chat',
          'chats',
          'conversation',
          'conversations',
          'dialog',
          'dialogs',
        ],
      },
      { name: createBase('less'), folderNames: ['less'] },
      {
        name: createBase('gulp'),
        folderNames: [
          'gulp',
          'gulp-tasks',
          'gulpfile.js',
          'gulpfile.mjs',
          'gulpfile.ts',
          'gulpfile.babel.js',
          'gulpfiles',
        ],
      },
      {
        name: createBase('python'),
        folderNames: ['python', 'pycache', 'pytest_cache'],
      },
      {
        name: createBase('sandbox'),
        folderNames: ['sandbox', 'sandboxes', 'playground', 'playgrounds'],
      },
      {
        name: createBase('scons'),
        folderNames: ['scons', 'sconf_temp', 'scons_cache'],
      },
      {
        name: createBase('mojo'),
        folderNames: ['mojo'],
      },
      { name: createBase('moon'), folderNames: ['moon'] },
      {
        name: createBase('debug'),
        folderNames: ['debug', 'debugger', 'debugging'],
      },
      { name: createBase('fastlane'), folderNames: ['fastlane'] },
      {
        name: createBase('plugin'),
        folderNames: [
          'plugin',
          'plugins',
          'mod',
          'mods',
          'modding',
          'extension',
          'extensions',
          'addon',
          'addons',
          'addin',
          'addins',
          'module',
          'modules',
        ],
      },
      {
        name: createBase('middleware'),
        folderNames: ['middleware', 'middlewares'],
      },
      {
        name: createBase('controller'),
        folderNames: [
          'controller',
          'controllers',
          'controls',
          'service',
          'services',
          'provider',
          'providers',
          'handler',
          'handlers',
        ],
      },
      { name: createBase('ansible'), folderNames: ['ansible'] },
      {
        name: createBase('server'),
        folderNames: [
          'server',
          'servers',
          'backend',
          'backends',
          'inventory',
          'inventories',
          'infrastructure',
          'infra',
        ],
      },
      {
        name: createBase('client'),
        folderNames: [
          'client',
          'clients',
          'frontend',
          'frontends',
          'pwa',
          'spa',
        ],
      },
      { name: createBase('tasks'), folderNames: ['tasks', 'tickets'] },
      { name: createBase('android'), folderNames: ['android'] },
      { name: createBase('ios'), folderNames: ['ios'] },
      {
        name: createBase('ui'),
        folderNames: ['presentation', 'gui', 'ui', 'ux'],
      },
      { name: createBase('upload'), folderNames: ['uploads', 'upload'] },
      {
        name: createBase('download'),
        folderNames: ['downloads', 'download', 'downloader', 'downloaders'],
      },
      {
        name: createBase('tools'),
        folderNames: [
          'tools',
          'toolkit',
          'toolkits',
          'toolbox',
          'toolboxes',
          'tooling',
          'devtools',
          'kit',
          'kits',
        ],
      },
      { name: createBase('helper'), folderNames: ['helpers', 'helper'] },
      { name: createBase('serverless'), folderNames: ['serverless'] },
      { name: createBase('api'), folderNames: ['api', 'apis', 'restapi'] },
      {
        name: createBase('app'),
        folderNames: ['app', 'apps', 'application', 'applications'],
      },
      {
        name: createBase('apollo'),
        folderNames: [
          'apollo',
          'apollo-client',
          'apollo-cache',
          'apollo-config',
        ],
      },
      {
        name: createBase('archive'),
        folderNames: ['arc', 'arcs', 'archive', 'archives', 'archival'],
      },
      {
        name: createBase('backup'),
        folderNames: [
          'bkp',
          'bkps',
          'bak',
          'baks',
          'backup',
          'backups',
          'back-up',
          'back-ups',
          'history',
          'histories',
        ],
      },
      {
        name: createBase('batch'),
        folderNames: ['batch', 'batchs', 'batches'],
      },
      { name: createBase('buildkite'), folderNames: ['buildkite'] },
      { name: createBase('cluster'), folderNames: ['cluster', 'clusters'] },
      {
        name: createBase('command'),
        folderNames: [
          'command',
          'commands',
          'commandline',
          'cmd',
          'cli',
          'clis',
        ],
      },
      {
        name: createBase('constant'),
        folderNames: ['constant', 'constants', 'const', 'consts'],
      },
      {
        name: createBase('container'),
        folderNames: ['container', 'containers', 'devcontainer'],
      },
      { name: createBase('content'), folderNames: ['content', 'contents'] },
      { name: createBase('context'), folderNames: ['context', 'contexts'] },
      { name: createBase('core'), folderNames: ['core'] },
      {
        name: createBase('delta'),
        folderNames: ['delta', 'deltas', 'changes'],
      },
      { name: createBase('dump'), folderNames: ['dump', 'dumps'] },
      {
        name: createBase('examples'),
        folderNames: [
          'demo',
          'demos',
          'example',
          'examples',
          'sample',
          'samples',
          'sample-data',
        ],
      },
      {
        name: createBase('environment'),
        folderNames: ['env', 'envs', 'environment', 'environments', 'venv'],
      },
      {
        name: createBase('functions'),
        folderNames: [
          'func',
          'funcs',
          'function',
          'functions',
          'lambda',
          'lambdas',
          'logic',
          'math',
          'maths',
          'calc',
          'calcs',
          'calculation',
          'calculations',
          'composable',
          'composables',
        ],
      },
      {
        name: createBase('generator'),
        folderNames: [
          'generator',
          'generators',
          'generated',
          'cfn-gen',
          'gen',
          'gens',
          'auto',
        ],
      },
      {
        name: createBase('hook'),
        folderNames: ['hook', 'hooks'],
      },
      {
        name: createBase('trigger'),
        folderNames: ['trigger', 'triggers'],
      },
      { name: createBase('job'), folderNames: ['job', 'jobs'] },
      {
        name: createBase('keys'),
        folderNames: [
          'key',
          'keys',
          'token',
          'tokens',
          'jwt',
          'secret',
          'secrets',
        ],
      },
      { name: createBase('layout'), folderNames: ['layout', 'layouts'] },
      {
        name: createBase('mail'),
        folderNames: ['mail', 'mails', 'email', 'emails', 'smtp', 'mailers'],
      },
      { name: createBase('mappings'), folderNames: ['mappings', 'mapping'] },
      { name: createBase('meta'), folderNames: ['meta', 'metadata'] },
      {
        name: createBase('changesets'),
        folderNames: ['changesets', 'changeset'],
      },
      {
        name: createBase('packages'),
        folderNames: [
          'package',
          'packages',
          'pkg',
          'pkgs',
          'serverpackages',
          'devpackages',
          'dependencies',
        ],
      },
      { name: createBase('shared'), folderNames: ['shared', 'common'] },
      {
        name: createBase('shader'),
        folderNames: ['glsl', 'hlsl', 'shader', 'shaders'],
      },
      { name: createBase('stack'), folderNames: ['stack', 'stacks'] },
      {
        name: createBase('template'),
        folderNames: [
          'template',
          'templates',
          'github/ISSUE_TEMPLATE',
          'github/PULL_REQUEST_TEMPLATE',
        ],
      },
      {
        name: createBase('utils'),
        folderNames: ['util', 'utils', 'utility', 'utilities'],
      },
      { name: createBase('supabase'), folderNames: ['supabase'] },
      { name: createBase('private'), folderNames: ['private'] },
      {
        name: createBase('linux'),
        folderNames: [
          'linux',
          'linuxbsd',
          'unix',
          'wsl',
          'ubuntu',
          'deb',
          'debian',
          'deepin',
          'centos',
          'popos',
          'mint',
        ],
      },
      {
        name: createBase('windows'),
        folderNames: [
          'windows',
          'win',
          'win32',
          'windows11',
          'windows10',
          'windowsxp',
          'windowsnt',
          'win11',
          'win10',
          'winxp',
          'winnt',
        ],
      },
      {
        name: createBase('macos'),
        folderNames: [
          'macos',
          'mac',
          'osx',
          'DS_Store',
          'iPhone',
          'iPad',
          'iPod',
          'macbook',
          'macbook-air',
          'macosx',
          'apple',
        ],
      },
      {
        name: createBase('error'),
        folderNames: ['error', 'errors', 'err', 'errs', 'crash', 'crashes'],
      },
      { name: createBase('event'), folderNames: ['event', 'events'] },
      {
        name: createBase('secure'),
        folderNames: [
          'auth',
          'authentication',
          'secure',
          'security',
          'cert',
          'certs',
          'certificate',
          'certificates',
          'ssl',
          'cipher',
          'cypher',
          'tls',
        ],
      },
      { name: createBase('custom'), folderNames: ['custom', 'customs'] },
      {
        name: createBase('mock'),
        folderNames: [
          'draft',
          'drafts',
          'mock',
          'mocks',
          'fixture',
          'fixtures',
          'concept',
          'concepts',
          'sketch',
          'sketches',
        ],
      },
      {
        name: createBase('syntax'),
        folderNames: ['syntax', 'syntaxes', 'spellcheck', 'spellcheckers'],
      },
      { name: createBase('vm'), folderNames: ['vm', 'vms'] },
      { name: createBase('stylus'), folderNames: ['stylus'] },
      { name: createBase('flow'), folderNames: ['flow-typed'] },
      {
        name: createBase('rules'),
        folderNames: [
          'rule',
          'rules',
          'validation',
          'validations',
          'validator',
          'validators',
        ],
      },
      {
        name: createBase('review'),
        folderNames: [
          'review',
          'reviews',
          'revisal',
          'revisals',
          'reviewed',
          'preview',
          'previews',
        ],
      },
      {
        name: createBase('animation'),
        folderNames: [
          'anim',
          'anims',
          'animation',
          'animations',
          'animated',
          'motion',
          'motions',
          'transition',
          'transitions',
          'easing',
          'easings',
        ],
      },
      { name: createBase('guard'), folderNames: ['guard', 'guards'] },
      {
        name: createBase('prisma'),
        folderNames: ['prisma', 'prisma/schema'],
      },
      {
        name: createBase('pipe'),
        folderNames: ['pipe', 'pipes', 'pipeline', 'pipelines'],
      },
      {
        name: createBase('interceptor'),
        folderNames: ['interceptor', 'interceptors'],
      },
      {
        name: createBase('svg'),
        folderNames: ['svg', 'svgs', 'vector', 'vectors'],
      },
      {
        name: createBase('vuex-store'),
        folderNames: ['store', 'stores'],
        enabledFor: [IconPack.Vuex],
      },
      {
        name: createBase('nuxt'),
        folderNames: ['nuxt'],
      },
      {
        name: createBase('vue-directives'),
        folderNames: ['directives'],
        enabledFor: [IconPack.Vuex, IconPack.Vue],
      },
      {
        name: createBase('vue'),
        folderNames: ['components'],
        enabledFor: [IconPack.Vuex, IconPack.Vue],
      },
      { name: createBase('terraform'), folderNames: ['terraform'] },
      {
        name: createBase('mobile'),
        folderNames: [
          'mobile',
          'mobiles',
          'portable',
          'portability',
          'phone',
          'phones',
        ],
      },
      { name: createBase('stencil'), folderNames: ['stencil'] },
      { name: createBase('firebase'), folderNames: ['firebase'] },
      {
        name: createBase('firestore'),
        folderNames: ['firestore', 'cloud-firestore', 'firebase-firestore'],
      },
      {
        name: createBase('cloud-functions'),
        folderNames: [
          'cloud-functions',
          'cloudfunctions',
          'firebase-cloud-functions',
          'firebase-cloudfunctions',
        ],
      },
      { name: createBase('svelte'), folderNames: ['svelte', 'svelte-kit'] },
      {
        name: createBase('update'),
        folderNames: ['update', 'updates', 'upgrade', 'upgrades'],
      },
      { name: createBase('intellij'), folderNames: ['idea'], light: true },
      {
        name: createBase('azure-pipelines'),
        folderNames: ['azure-pipelines', 'azure-pipelines-ci'],
      },
      { name: createBase('mjml'), folderNames: ['mjml'] },
      {
        name: createBase('admin'),
        folderNames: [
          'admin',
          'admins',
          'manager',
          'managers',
          'moderator',
          'moderators',
        ],
      },
      {
        name: createBase('jupyter'),
        folderNames: ['jupyter', 'notebook', 'notebooks', 'ipynb'],
      },
      { name: createBase('scala'), folderNames: ['scala'] },
      {
        name: createBase('connection'),
        folderNames: [
          'connection',
          'connections',
          'integration',
          'integrations',
          'remote',
          'remotes',
        ],
      },
      { name: createBase('quasar'), folderNames: ['quasar'] },
      { name: createBase('next'), folderNames: ['next'] },
      {
        name: createBase('dal'),
        folderNames: ['dal', 'data-access', 'data-access-layer'],
      },
      { name: createBase('cobol'), folderNames: ['cobol'] },
      { name: createBase('yarn'), folderNames: ['yarn'] },
      { name: createBase('husky'), folderNames: ['husky'] },
      {
        name: createBase('storybook'),
        folderNames: ['storybook', 'stories'],
      },
      { name: createBase('base'), folderNames: ['base', 'bases'] },
      {
        name: createBase('cart'),
        folderNames: ['cart', 'shopping-cart', 'shopping', 'shop'],
      },
      {
        name: createBase('home'),
        folderNames: ['home', 'start', 'main', 'landing'],
      },
      {
        name: createBase('project'),
        folderNames: ['project', 'projects', 'proj', 'projs'],
      },
      {
        name: createBase('prompts'),
        folderNames: ['prompt', 'prompts'],
      },
      {
        name: createBase('interface'),
        folderNames: ['interface', 'interfaces'],
      },
      { name: createBase('netlify'), folderNames: ['netlify'] },
      {
        name: createBase('enum'),
        folderNames: ['enum', 'enums'],
      },
      {
        name: createBase('contract'),
        folderNames: [
          'pact',
          'pacts',
          'contract',
          'contracts',
          'contract-testing',
          'contract-test',
          'contract-tests',
        ],
      },
      {
        name: createBase('helm'),
        folderNames: ['helm', 'helmchart', 'helmcharts'],
      },
      {
        name: createBase('queue'),
        folderNames: ['queue', 'queues', 'bull', 'mq'],
      },
      {
        name: createBase('vercel'),
        folderNames: ['vercel', 'now'],
      },
      {
        name: createBase('cypress'),
        folderNames: ['cypress'],
      },
      {
        name: createBase('decorators'),
        folderNames: ['decorator', 'decorators'],
      },
      {
        name: createBase('java'),
        folderNames: ['java'],
      },
      {
        name: createBase('resolver'),
        folderNames: ['resolver', 'resolvers'],
      },
      {
        name: createBase('angular'),
        folderNames: ['angular'],
      },
      {
        name: createBase('unity'),
        folderNames: ['unity'],
      },
      {
        name: createBase('pdf'),
        folderNames: ['pdf', 'pdfs'],
      },
      {
        name: createBase('proto'),
        folderNames: ['protobuf', 'protobufs', 'proto', 'protos'],
      },
      {
        name: createBase('plastic'),
        folderNames: ['plastic'],
      },
      {
        name: createBase('gamemaker'),
        folderNames: ['gamemaker', 'gamemaker2'],
      },
      {
        name: createBase('mercurial'),
        folderNames: ['hg', 'hghooks', 'hgext'],
      },
      {
        name: createBase('godot'),
        folderNames: ['godot', 'godot-cpp'],
      },
      {
        name: createBase('lottie'),
        folderNames: ['lottie', 'lotties', 'lottiefiles'],
      },
      {
        name: createBase('taskfile'),
        folderNames: ['taskfile', 'taskfiles'],
      },
      {
        name: createBase('drizzle'),
        folderNames: ['drizzle'],
      },
      {
        name: createBase('cloudflare'),
        folderNames: ['cloudflare'],
      },
      {
        name: createBase('seeders'),
        folderNames: ['seeds', 'seeders', 'seed', 'seeding'],
      },
      {
        name: createBase('store'),
        folderNames: ['store', 'stores'],
        enabledFor: [IconPack.Angular],
      },
      { name: createBase('bicep'), folderNames: ['bicep'] },
      { name: createBase('snapcraft'), folderNames: ['snap', 'snapcraft'] },
      {
        name: createBase('development'),
        folderNames: ['dev', 'development'],
        clone: {
          base: 'folder-src',
          color: createCloneColor('blue'),
        },
      },
      { name: createBase('flutter'), folderNames: ['flutter'] },
      { name: createBase('snippet'), folderNames: ['snippet', 'snippets'] },
      { name: createBase('element'), folderNames: ['element', 'elements'] },
      {
        name: createBase('src-tauri'),
        folderNames: ['src-tauri'],
      },
      {
        name: createBase('favicon'),
        folderNames: ['favicon', 'favicons'],
      },
      {
        name: createBase('features'),
        folderNames: ['feature', 'features', 'feat', 'feats'],
      },
      {
        name: createBase('lefthook'),
        folderNames: ['lefthook', 'lefthook-local'],
      },
      {
        name: createBase('bloc'),
        folderNames: ['bloc', 'cubit', 'blocs', 'cubits'],
      },
      {
        name: createBase('powershell'),
        folderNames: ['powershell', 'ps', 'ps1'],
      },
      {
        name: createBase('repository'),
        folderNames: ['repository', 'repositories', 'repo', 'repos'],
      },
      {
        name: createBase('luau'),
        folderNames: ['luau'],
      },
      { name: createBase('obsidian'), folderNames: ['obsidian'] },
      { name: createBase('trash'), folderNames: ['trash'] },
      { name: createBase('cline'), folderNames: ['cline_docs'] },
      { name: createBase('liquibase'), folderNames: ['liquibase'] },
      {
        name: createBase('dart'),
        folderNames: ['dart', 'dart_tool', 'dart_tools'],
      },
      { name: createBase('zeabur'), folderNames: ['zeabur'] },
      { name: createBase('kusto'), folderNames: ['kusto', 'kql'] },
      { name: createBase('policy'), folderNames: ['policy', 'policies'] },
      {
        name: createBase('attachment'),
        folderNames: ['attachment', 'attachments'],
      },
      {
        name: createBase('bibliography'),
        folderNames: ['bibliography', 'bibliographies', 'book', 'books'],
      },
      { name: createBase('link'), folderNames: ['link', 'links'] },
      { name: createBase('pytorch'), folderNames: ['pytorch', 'torch'] },
      {
        name: createBase('blender'),
        folderNames: [
          'blender',
          'blender-assets',
          'blender-files',
          'blender-project',
          'blender-models',
        ],
      },
      {
        name: createBase('atom'),
        folderNames: ['atoms', 'atom'],
      },
      {
        name: createBase('molecule'),
        folderNames: ['molecules', 'molecule'],
      },
      {
        name: createBase('organism'),
        folderNames: ['organisms', 'organism'],
      },
      {
        name: createBase('claude'),
        folderNames: ['.claude'],
      },
      {
        name: createBase('cursor'),
        folderNames: ['.cursor'],
        light: true,
      },
      {
        name: createBase('gemini-ai'),
        folderNames: ['.gemini', 'gemini', 'gemini-ai', 'geminiai'],
      },
      {
        name: createBase('input'),
        folderNames: ['input', 'inputs', 'io', 'in'],
      },
      {
        name: createBase('salt'),
        folderNames: ['salt', 'saltstack'],
      },
      {
        name: createBase('simulations'),
        folderNames: ['simulations', 'simulation', 'sim', 'sims'],
      },
      {
        name: createBase('metro'),
        folderNames: ['metro'],
      },
      {
        name: createBase('filter'),
        folderNames: ['filter', 'filters'],
      },
      {
        name: createBase('toc'),
        folderNames: ['toc', 'table-of-contents'],
      },
      {
        name: createBase('cue'),
        folderNames: ['cue', 'cues'],
      },
      {
        name: createBase('license'),
        folderNames: ['license', 'licenses'],
      },
    ],
  };
}
